// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OBeefSoup.Data;

#nullable disable

namespace OBeefSoup.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220092141_RestoreBackgroundData")]
    partial class RestoreBackgroundData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OBeefSoup.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@obeefsoup.vn",
                            FullName = "Quản Trị Viên",
                            IsActive = true,
                            PasswordHash = "F65121EE9DA8E3AEEFBA5B0A795D8D851F07EF218808764179E8AEACE08EE132",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manager@obeefsoup.vn",
                            FullName = "Quản Lý Nội Dung",
                            IsActive = true,
                            PasswordHash = "57EB76546AEF06B06AE1941B25E76573D35CD29BCE27A66BE14271823BDC8BA4",
                            Role = "Manager",
                            Username = "manager"
                        });
                });

            modelBuilder.Entity("OBeefSoup.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Banners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 2, 20, 16, 21, 41, 105, DateTimeKind.Local).AddTicks(8406),
                            Description = "Phở Bò Ngon Nhất Hà Nội - Hương Vị Truyền Thống",
                            DisplayOrder = 1,
                            ImageUrl = "https://placehold.co/1200x400/8B0000/FFF?text=O'+BeefSoup+Banner",
                            IsActive = true,
                            Link = "/Menu",
                            Title = "Chào Mừng Đến Với O' BeefSoup"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 2, 20, 16, 21, 41, 105, DateTimeKind.Local).AddTicks(8409),
                            Description = "Giảm 20% Cho Đơn Hàng Đầu Tiên",
                            DisplayOrder = 2,
                            ImageUrl = "https://placehold.co/1200x400/FFB347/000?text=Khuyen+Mai",
                            IsActive = true,
                            Link = "/Menu",
                            Title = "Khuyến Mãi Đặc Biệt"
                        });
                });

            modelBuilder.Entity("OBeefSoup.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Các loại phở bò truyền thống",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Phở Bò"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Phở gà thanh đạm, thơm ngon",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Phở Gà"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nước giải khát",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Đồ Uống"
                        });
                });

            modelBuilder.Entity("OBeefSoup.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastOrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("OBeefSoup.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            Title = "Trang Chủ",
                            Url = "/"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            Title = "Giới Thiệu",
                            Url = "/#about"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            Title = "Thực Đơn",
                            Url = "/Menu"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsActive = true,
                            Title = "Ưu Điểm",
                            Url = "/#why-us"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            IsActive = true,
                            Title = "Đánh Giá",
                            Url = "/#testimonials"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 1,
                            IsActive = true,
                            ParentId = 3,
                            Title = "Phở Bò",
                            Url = "/Menu#category-1"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 2,
                            IsActive = true,
                            ParentId = 3,
                            Title = "Phở Gà",
                            Url = "/Menu#category-2"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 3,
                            IsActive = true,
                            ParentId = 3,
                            Title = "Đồ Uống",
                            Url = "/Menu#category-3"
                        });
                });

            modelBuilder.Entity("OBeefSoup.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OBeefSoup.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OBeefSoup.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 2, 20, 16, 21, 41, 105, DateTimeKind.Local).AddTicks(8276),
                            Description = "Thịt bò tái mềm, nước dùng thanh ngọt",
                            ImageUrl = "/images/pho-bo-tai-nam.jpg",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Phở Tái",
                            Price = 65000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 2, 20, 16, 21, 41, 105, DateTimeKind.Local).AddTicks(8279),
                            Description = "Gầu bò béo ngậy, đậm đà truyền thống",
                            ImageUrl = "/images/pho-bo-chin.jpg",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Phở Gầu",
                            Price = 70000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 2, 20, 16, 21, 41, 105, DateTimeKind.Local).AddTicks(8281),
                            Description = "Đầy đủ topping - Signature O' BeefSoup",
                            ImageUrl = "https://placehold.co/400x300/8B0000/FFF?text=Pho+Dac+Biet",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Phở Đặc Biệt",
                            Price = 85000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 2, 20, 16, 21, 41, 105, DateTimeKind.Local).AddTicks(8282),
                            Description = "Nạm bò thơm ngon, mềm tan",
                            ImageUrl = "https://placehold.co/400x300/8B0000/FFF?text=Pho+Nam",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Phở Nạm",
                            Price = 68000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 2, 20, 16, 21, 41, 105, DateTimeKind.Local).AddTicks(8285),
                            Description = "Bò viên giòn sần sật",
                            ImageUrl = "https://placehold.co/400x300/8B0000/FFF?text=Pho+Bo+Vien",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Phở Bò Viên",
                            Price = 60000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 2, 20, 16, 21, 41, 105, DateTimeKind.Local).AddTicks(8287),
                            Description = "Gà ta thơm ngon, nước dùng thanh ngọt",
                            ImageUrl = "https://placehold.co/400x300/FFB347/000?text=Pho+Ga",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Phở Gà",
                            Price = 55000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 2, 20, 16, 21, 41, 105, DateTimeKind.Local).AddTicks(8289),
                            Description = "Gà ta nguyên con, đầy đủ topping",
                            ImageUrl = "https://placehold.co/400x300/FFB347/000?text=Pho+Ga+Dac+Biet",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Phở Gà Đặc Biệt",
                            Price = 75000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 2, 20, 16, 21, 41, 105, DateTimeKind.Local).AddTicks(8291),
                            Description = "Trà đá miễn phí",
                            ImageUrl = "https://placehold.co/400x300/5E8B7E/FFF?text=Tra+Da",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Trà Đá",
                            Price = 0m,
                            Stock = 1000
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 2, 20, 16, 21, 41, 105, DateTimeKind.Local).AddTicks(8293),
                            Description = "Coca, Pepsi, 7Up",
                            ImageUrl = "https://placehold.co/400x300/FF6347/FFF?text=Nuoc+Ngot",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Nước Ngọt",
                            Price = 15000m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 2, 20, 16, 21, 41, 105, DateTimeKind.Local).AddTicks(8295),
                            Description = "Chanh tươi vắt",
                            ImageUrl = "https://placehold.co/400x300/FFE135/000?text=Nuoc+Chanh",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Nước Chanh",
                            Price = 20000m,
                            Stock = 100
                        });
                });

            modelBuilder.Entity("OBeefSoup.Models.SiteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 2, 20, 16, 21, 41, 105, DateTimeKind.Local).AddTicks(8433),
                            Description = "Ảnh nền cho phần thực đơn trang chủ",
                            IsActive = true,
                            Key = "MenuBackgroundImage",
                            Value = "/images/menu-background.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 2, 20, 16, 21, 41, 105, DateTimeKind.Local).AddTicks(8435),
                            Description = "Độ mờ ảnh nền thực đơn (0.0 = trong suốt, 1.0 = rõ nét).",
                            IsActive = true,
                            Key = "MenuBackgroundOpacity",
                            Value = "0.15"
                        });
                });

            modelBuilder.Entity("OBeefSoup.Models.StoreLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MapUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StoreLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh",
                            City = "Hồ Chí Minh",
                            Email = "contact@obeefsoup.vn",
                            IsActive = true,
                            MapUrl = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.513274291583!2d106.70119131533413!3d10.771143262222383!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f40a3b49e59%3A0xe27581172a39a037!2zMTIzIMSQLiBOZ3V54buFbiBIdeG7hywgQuG6v24gTmdow6ks QuG6rW4gMSwgVGjDoW5oIHBo4buSIEjhu5MgQ2jDrSBNaW5oLCBWaWV0bmFt!5e0!3m2!1sen!2s!4v1645084931345!5m2!1sen!2s",
                            Name = "O' BeefSoup - Chi nhánh Trung tâm",
                            OpeningHours = "7:00 - 22:00 (Hàng ngày)",
                            Phone = "0901 234 567"
                        });
                });

            modelBuilder.Entity("OBeefSoup.Models.MenuItem", b =>
                {
                    b.HasOne("OBeefSoup.Models.MenuItem", "Parent")
                        .WithMany("SubMenus")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OBeefSoup.Models.Order", b =>
                {
                    b.HasOne("OBeefSoup.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OBeefSoup.Models.OrderItem", b =>
                {
                    b.HasOne("OBeefSoup.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBeefSoup.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OBeefSoup.Models.Product", b =>
                {
                    b.HasOne("OBeefSoup.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OBeefSoup.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OBeefSoup.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OBeefSoup.Models.MenuItem", b =>
                {
                    b.Navigation("SubMenus");
                });

            modelBuilder.Entity("OBeefSoup.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
